import '../../data/models/station.dart';

final List<Station> fallbackStations = [
  Station(
    changeuuid: "vividh-bharti",
    name: "Vividh Bharti",
    url: "https://air.pc.cdn.bitgravity.com/air/live/pbaudio070/playlist.m3u8",
    urlResolved: "https://air.pc.cdn.bitgravity.com/air/live/pbaudio070/playlist.m3u8",
    homepage: "https://prasarbharati.gov.in/",
    favicon: "https://raw.githubusercontent.com/rupesh-sontakke/RFM/main/public/stations/vividh_bharti.png",
    tags: "classic,bollywood,news,national",
    country: "India",
    state: "National",
    votes: 1500,
  ),
  Station(
    changeuuid: "radio-mirchi-nagpur",
    name: "Radio Mirchi 98.3",
    url: "https://eu8.fastcast4u.com/proxy/clyedupq?mp=%2F1?aw_0_req_lsid=2c0fae177108c9a42a7cf24878625444",
    urlResolved: "https://eu8.fastcast4u.com/proxy/clyedupq?mp=%2F1?aw_0_req_lsid=2c0fae177108c9a42a7cf24878625444",
    homepage: "https://www.radiomirchi.com/",
    favicon: "https://raw.githubusercontent.com/rupesh-sontakke/RFM/main/public/stations/radio_mirchi.png",
    tags: "bollywood,hits,top40,nagpur",
    country: "India",
    state: "Maharashtra",
    votes: 1200,
  ),
  Station(
    changeuuid: "big-fm-927",
    name: "BIG 92.7 FM",
    url: "https://stream.zeno.fm/dbstwo3dvhhtv",
    urlResolved: "https://stream.zeno.fm/dbstwo3dvhhtv",
    homepage: "https://www.bigfmindia.com/",
    favicon: "https://raw.githubusercontent.com/rupesh-sontakke/RFM/main/public/stations/big_fm.png",
    tags: "bollywood,retro,talk,nagpur",
    country: "India",
    state: "Maharashtra",
    votes: 1100,
  ),
  Station(
    changeuuid: "radio-city-911-nagpur",
    name: "Radio City 91.1",
    url: "https://stream.zeno.fm/pxc55r5uyc9uv",
    urlResolved: "https://stream.zeno.fm/pxc55r5uyc9uv",
    homepage: "https://www.radiocity.in/",
    favicon: "https://raw.githubusercontent.com/rupesh-sontakke/RFM/main/public/stations/radio_city.png",
    tags: "bollywood,hits,nagpur",
    country: "India",
    state: "Maharashtra",
    votes: 1050,
  ),
  Station(
    changeuuid: "red-fm-935-nagpur",
    name: "Red FM 93.5",
    url: "https://stream.zeno.fm/9phrkb1e3v8uv",
    urlResolved: "https://stream.zeno.fm/9phrkb1e3v8uv",
    homepage: "https://www.redfmindia.in/",
    favicon: "https://raw.githubusercontent.com/rupesh-sontakke/RFM/main/public/stations/red_fm.png",
    tags: "bollywood,hits,nagpur",
    country: "India",
    state: "Maharashtra",
    votes: 1000,
  ),
];
